name: Register Alert

on:
  issues:
    types:
      - opened

jobs:
  register-alert:
    runs-on: ubuntu-latest
    permissions:
      # issues: write
      # contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Update Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ISSUE_TOKEN }}
          script: |
            const update = require('./scripts/issue-update.js')
            update({ github, context })
